### ISSUE TITLE
Use eslint

### ISSUE THREAD

**Issue by pmyers88** [pmyers88/dc-metro-echo#28]

**Comment by r33beers** [comment]
What eslint standard do you want to use? google, airbnb, standard, or something else?

**Comment by pmyers88** [comment]
Thinking of using [standard](https://github.com/feross/standard) instead.

**Comment by r33beers** [comment]
Ok. That sounds good. I could give no semicolons a try. The rests sounds pretty "standard".

**Comment by pmyers88** [comment]
I actually picked [semistandard](https://github.com/Flet/semistandard), which is standard with semicolons. It's in the `linter` branch; will created a PR once #32 gets merged.

**Comment by r33beers** [comment]
Closed by #34
