### ISSUE TITLE
Variations on stop names should be understood

### ISSUE THREAD

**Issue by r33beers** [pmyers88/dc-metro-echo#31]
I think everyone has a name for their stop that is not what the API returns. We should take a look at what people call their stops and then implement matchers, so we not only match speech correctly to the stop but also announce the stop in a more casual way.

For instance, "Wiehle Reston East" could be asked for as "Reston" or "Wiehle." We want to understand both, but also, we probably want to just announce it as "Reston" when the echo says it.

**Comment by pmyers88** [comment]
Duplicates #45
