### ISSUE TITLE
What is the license for this repo?

### ISSUE THREAD

**Issue by r33beers** [pmyers88/dc-metro-echo#41]
@pmyers88 the package.json says MIT license, but there is an Apache LICENSE.md. What's going on?

**Comment by pmyers88** [comment]
The Alexa API license is Apache. I thought that meant we'd have to use the Apache license. Do you know if that's the case?

**Comment by r33beers** [comment]
Apache requires license and disclaimer to be kept with the code, so maybe we should move those into the vendor folder?

**Comment by r33beers** [comment]
Then MIT license could possibly be put in LICENSE.md

**Comment by pmyers88** [comment]
Ah. I kept the license in the Alexa code, so it's probably not necessary to move it. We can switch back to MIT.
