### ISSUE TITLE
Better voice interface when there is one station option

### ISSUE THREAD

**Issue by pmyers88** [pmyers88/dc-metro-echo#44]
When it's close to closing, there may only be 1 train arriving at the requested station. This is how the current voice interface works:

> When is the next train arriving at Ballston?
> Are you going to Vienna?
> Yes.
> Sorry, there was a problem with the requested skills response.

Maybe switch to:
> When is the next train arriving at Ballston?
> The next train from Ballston to Vienna arrives in 8 minutes. There are no other trains arriving at Ballston in the next 20 minutes.

**Comment by r33beers** [comment]
Do we handle it well if there are no trains at all?

**Comment by pmyers88** [comment]
Yea, we say "Sorry, there are no trains running at this time".
