### ISSUE TITLE
Sanitize Service Advisory Text

### ISSUE THREAD

**Issue by pmyers88** [pmyers88/dc-metro-echo#47]
Service advisories use "btw" instead of "between". Fix this and check for other abbreviations.

**Comment by r33beers** [comment]
Can you provide a little more detail for this? Maybe an example?

**Comment by pmyers88** [comment]
Here's an example:

> "Blu/Org Line: Single tracking btwn Stadium-Armory & Eastern Market due to scheduled track work. Expect delays through tonight's closing."
