### ISSUE TITLE
Switch to custom slots for GetServiceAdvisories

### ISSUE THREAD

**Issue by pmyers88** [pmyers88/dc-metro-echo#49]
Whenever I attempt to call the `GetStationDestination` intent, Alexa performs calls the `GetServiceAdvisories` intent instead. I think this may be because our sample utterances for `GetStationDestination` and `GetServiceAdvisories` are both one word.

We should be able to use [custom slots](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/migrating-to-the-improved-built-in-and-custom-slot-types) to replicate the enumeration of words we currently accept for advisory intents. Hopefully this would prevent confusion.

**Comment by r33beers** [comment]
What are you saying to reproduce this issue?

**Comment by r33beers** [comment]
I think I see what you mean though. We could define a custom type that enumerates all possible station names. This could help us recognize the responses, but then, we are white listing the stations including things like Boston for ballston. If not, it won't be recognized.

**Comment by pmyers88** [comment]
I'm asking for trains arriving at Ballston and then saying "Vienna" for where I want to go. I've seen it happen for other stations too. Were you not able to reproduce?

As for custom slots for stations, I agree that wouldn't be as easy of a transition. Next release.
